### ISSUE TITLE
Не работают left & right на моделировании

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/webGraphicsFishenko#11]
![screenshot_217](https://cloud.githubusercontent.com/assets/9131239/24658972/b157f368-198e-11e7-9d4d-8f575ab5ee92.png)

**Comment by klasterstorm** [comment]
В окне моделирования нет функции зума. Почитай Лаба №4.

**Comment by bezgodov** [comment]
@klasterstorm хм, у меня прост в проге работало :3

**Comment by klasterstorm** [comment]
@bezgodov В окне моделирования нет никакого функционала. Есть только возможность моделирования сигналов, с помощью изменения значений в полях. Еще есть возможность добавления смоделированного сигнала в общий массив, с последующим добавлением в осциллограмму.

**Comment by bezgodov** [comment]
@klasterstorm мне кажется удобно :3 [старая прога]
![screenshot_220](https://cloud.githubusercontent.com/assets/9131239/24690758/605fd7d0-1a12-11e7-8376-c308d8d4fb1a.png)
![screenshot_219](https://cloud.githubusercontent.com/assets/9131239/24690759/60ac4174-1a12-11e7-9d17-c62beb0eaee7.png)

**Comment by klasterstorm** [comment]
@bezgodov ты прицепи ресайз к окну, и будет так же
