### ISSUE TITLE
Окна сделать одинаковыми

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/webGraphicsFishenko#12]
Добавил перемещение для модального окна и теперь они ничем не отличаются от других окон, а зачем тогда надо? Можно и поменять, а то непонятно почему они разные и будет хорошо, если использовать одно окно ui-widget-%smt%, то будет легче работать и удобнее, сделать кнопку, которую можно будет вставить [кнопка "ОК"] и будет замечательно.
![screenshot_218](https://cloud.githubusercontent.com/assets/9131239/24690729/28475b34-1a12-11e7-9e2c-2952e59a2bf4.png)

**Comment by klasterstorm** [comment]
<img width="1247" alt="2017-04-05 19 43 06" src="https://cloud.githubusercontent.com/assets/8971579/24699675/2c00d25c-1a38-11e7-8414-d26249836323.png">
