### ISSUE TITLE
Кнопка для добавления смоделированного сигнала к текущим каналам

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/webGraphicsFishenko#13]
Где-то рядом
![screenshot_221](https://cloud.githubusercontent.com/assets/9131239/24691293/f9e66592-1a15-11e7-95b7-3f3044361fab.png)

**Comment by klasterstorm** [comment]
<img width="179" alt="2017-04-05 19 40 26" src="https://cloud.githubusercontent.com/assets/8971579/24699569/c75eb1a2-1a37-11e7-8a37-70b3974686f1.png">
