### ISSUE TITLE
Линии накладываются на график

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/webGraphicsFishenko#16]
![2017-04-25 20 04 11](https://cloud.githubusercontent.com/assets/9131239/25381611/c8f1a874-29f7-11e7-9440-4dd325ad6bee.png)

**Comment by klasterstorm** [comment]
![2017-04-27 1 01 15](https://cloud.githubusercontent.com/assets/8971579/25441277/1614c724-2ae5-11e7-9cd8-a24db7dc7a3e.png)
