### ISSUE TITLE
В моделирование ось X "статистическая"

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/webGraphicsFishenko#4]
Не растягивается по количеству отчётов
![2017-04-03 23 13 09](https://cloud.githubusercontent.com/assets/9131239/24610812/59e68444-18c3-11e7-9962-f46c74e25e6d.png)
![2017-04-03 23 13 16](https://cloud.githubusercontent.com/assets/9131239/24610814/59e8e81a-18c3-11e7-9dae-1297d3d1ed84.png)
![2017-04-03 23 13 22](https://cloud.githubusercontent.com/assets/9131239/24610813/59e78cfe-18c3-11e7-8ec3-02d07d3b23a2.png)

**Comment by klasterstorm** [comment]
Модель была сделана по тестам выше
<img width="314" alt="2017-04-05 1 01 31" src="https://cloud.githubusercontent.com/assets/8971579/24663515/75b3a8fe-199b-11e7-932e-b8d96ebcee32.png">

**Comment by bezgodov** [comment]
@klasterstorm хм, у меня прост в проге работало :3
