### ISSUE TITLE
В осциллограмме не отображается ось Х

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/webGraphicsFishenko#5]
![2017-04-03 23 15 16](https://cloud.githubusercontent.com/assets/9131239/24610883/96e652ca-18c3-11e7-85e5-65aefca7c7cd.png)

**Comment by klasterstorm** [comment]
<img width="540" alt="2017-04-05 1 05 52" src="https://cloud.githubusercontent.com/assets/8971579/24663728/17aee34e-199c-11e7-96ad-4154e9022517.png">
