### ISSUE TITLE
Интерфейс для локальный/глобальный масштаб

### ISSUE THREAD

**Issue by bezgodov** [bezgodov/webGraphicsFishenko#9]

**Comment by klasterstorm** [comment]
Он уже есть, и это выпадающее меню(ПКМ)
Наш интерфейс:
<img width="219" alt="2017-04-04 14 26 11" src="https://cloud.githubusercontent.com/assets/8971579/24663346/0197bf0a-199b-11e7-86a4-536691421ebb.png">
Интерфейс Фищенко:
<img width="323" alt="2017-04-05 0 57 13" src="https://cloud.githubusercontent.com/assets/8971579/24663347/027f2340-199b-11e7-91ce-508897e6fc99.png">
